### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [kcprs/audio-rest#1]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/forart/HyMPS#- ) \ [Treatments page](https://github.com/forart/HyMPS/blob/main/Audio/Treatments.md#-- ) \ [Restoring](https://github.com/forart/HyMPS/blob/main/Audio/Treatments.md#restoring-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/kcprs/audio-rest)
(badge-generator URL: https://badgen.net/github/license/kcprs/audio-rest)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by kcprs** [comment]
Hi,

It's nice to see that my old Master's project is useful to someone. I've added a license file.

**Comment by MarcoRavich** [comment]
Thanks for adding a license file (as you can see the badge is now correctly generated too) !

We do strongly believe that any open source code can be useful even if it's un-updated/maintained, but if this is the case, we suggest you to set your repository as archived (so the "no longer developed" state will be clearer for anyone).

Last but not least: our [GH organization](https://github.com/FORARTfe) has started to store development-deadlocked third-party source codes in order to preserve them from the oblivion, so - if you're considering to get rid of this repository - we strongly invite you to donate it (using the [GH Transfer function](https://github.com/kcprs/audio-rest/transfer)) instead of deleting.

Thanks again !

**Comment by kcprs** [comment]
Good point, I will archive the repo.
